bookers/config/routes.rb
Rails.application.routes.draw do
devise_for :users
 root 'home#top'
 get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users, only: [:show, :edit, :index, :update, :destroy]
resources :books 
end

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <h2 class="headtitle">Bookers</h2>
    </div>
    <ul class="nav navbar-nav">
      
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><%= link_to ' Home', user_path(current_user.id), class:"glyphicon glyphicon-home" %></li>
      <li><%= link_to ' Users', users_path, class:"glyphicon glyphicon-user" %></li>
      <li><%= link_to ' Books', books_path, class:"glyphicon glyphicon-book" %></li>
      <li><%= link_to ' logout', destroy_user_session_path,method: :delete, class:"glyphicon glyphicon-log-out" %></li>
      <% else %>
      <li><%= link_to ' Home', root_path, class:"glyphicon glyphicon-home" %></li>
      <li><%= link_to ' About', home_about_path, class:"glyphicon glyphicon-link" %></li>
      <li><%= link_to ' sign Up', new_user_registration_path, class:"glyphicon glyphicon-user" %></li>
      <li><%= link_to ' login', new_user_session_path, class:"glyphicon glyphicon-log-in" %></li>
      <% end %>
    </ul>
  </div>
</nav>
<div class="container">
  <p id="notice"><%= notice %></p>
</div>

<%= yield %>
</body>
</html>